title: Clan Conan
# email:
description: >-
  Personal site to share updates on life,
  travel, and programming projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://michaelconan.github.io"
github_username:  michaelconan

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed

github:
  is_project_page: true
